### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by rodchenkov** [PaulMiami/reCAPTCHA#1]
Hi
Can you please add language support?
Thank you!

**Comment by PaulMiami** [comment]
hi, sure thing

**Comment by PaulMiami** [comment]
Download 1.1.0 from [nuget](https://www.nuget.org/packages/PaulMiami.AspNetCore.Mvc.Recaptcha/1.1.0) and check out the [documentation](https://github.com/PaulMiami/reCAPTCHA/wiki/Localization-support), let me know if you have a problem
