### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by Zain-Alabdin** [PaulMiami/reCAPTCHA#10]
I have a page where I want to submit the form using Ajax to another method (not same name as page) and I want to validate Captcha... is it possible and can you please explain how?

**Comment by PaulMiami** [comment]
Yes, add the attribute "[ValidateRecaptcha]" to the action you are posting to and check that "ModelState.IsValid" is valid, it's pretty much the same a non-ajax call.

```csharp
[ValidateRecaptcha]
[HttpPost]
public IActionResult SomeAction(SomeViewModel viewModel)
{
    if (ModelState.IsValid)
    {
         return Json(new { Success = true});
    }
    return Json(new { Success = false });
}
```

Try something like this for your javascript:
```html
@section Scripts {
    <recaptcha-script jquery-validation="false" />
    <script>
        $(function () {
            $("#submit").click(function () {
                $.post("/SomeAction", $("form").serialize());
            });
        });
    </script>
}
```

If you need to reset the captcha call:
```javascript
grecaptcha.reset()
```

**Comment by PaulMiami** [comment]
reopen the issue if you have more questions
