### ISSUE TITLE
How to add callback onsubmit with recaptcha?

### ISSUE THREAD

**Issue by Mergasov** [PaulMiami/reCAPTCHA#12]
Hi, I have a question.
I have the following callback onsubmit for form with recaptcha tag helper:
```
$("form").on("submit", function() {
     if($(this).valid()){
        // do something before submit...
   }
})
```
The issue is `valid() ` returns true when user doesn't resolve recaptcha yet. How can I change this behavior?

**Comment by PaulMiami** [comment]
Hi,

you need to check if the repcaptcha as been answered first with:

```javascript
$("form").on("submit", function() {
     if(grecaptcha.getResponse() !== "" && $(this).valid()){
        // do something before submit...
   }
})
```
