### ISSUE TITLE
Recaptcha in one form is blocking another form

### ISSUE THREAD

**Issue by jepperaskdk** [PaulMiami/reCAPTCHA#17]
I have described the issue in this StackOverflow thread:
[https://stackoverflow.com/questions/45131662/recaptcha-in-one-form-is-blocking-another-form](url)

**Comment by PaulMiami** [comment]
This was a bug, it was fixed in version 1.2.1, please update:

    dotnet add package PaulMiami.AspNetCore.Mvc.Recaptcha --version 1.2.1
