### ISSUE TITLE
How can I use recaptcha conditionally?

### ISSUE THREAD

**Issue by egmfrs** [PaulMiami/reCAPTCHA#18]
I have put the [ValidateRecaptcha] attribute on the controller action.
However my view has a razor condition so that the captcha is only rendered on the page if the user has previously entered invalid credentials in that session.

So for the first attempt at logging in, the user is not required to complete a captcha.
If I include the validation attribute, the user cannot log in. If I leave off the attribute, it works but the user is not alerted with unobtrusive validation if they do not tick "I'm not a robot".

Is it possible for you to amend the code behind the attribute to only come into play if there was a captcha element rendered in the view?

Many thanks for this package and clear documentation.

**Comment by PaulMiami** [comment]
It would kind of defeat the purpose of the validation, if you could just bypass the check if the captcha is missing

**Comment by egmfrs** [comment]
Have you any ideas on how I could implement this most effectively then? (recaptcha only if incorrect details entered N times)
I have account lock out set up at 5 attempts but this wouldn't stop a brute force where different login names are tried against single password.

**Comment by PaulMiami** [comment]
I guess you could have 2 actions on you controller. First one, that is your regular login where you check that the number of failed login attempt is below what requires a captcha, the second one with recaptcha validation. Then on the view render the appropriate form action and recaptcha depending on your failed login retry logic

**Comment by egmfrs** [comment]
Thanks, that sounds good.
