### ISSUE TITLE
"Getting started" need additional details on displaying error messages

### ISSUE THREAD

**Issue by neoGeneva** [PaulMiami/reCAPTCHA#19]
Currently the documentation doesn't mention the `validation-message-element-id` property on `recaptcha-script`, and the scripts generated will generate jQuery errors if it isn't set.

The other missing is how to display error messages passed from server side, currently set with `ModelState.AddModelError("g-recaptcha-response", ...)`

The code I ended up using for both of the above ended up looking something like this:

```html
<div class="form-group">
    <recaptcha />
    @Html.ValidationMessage("g-recaptcha-response", new { @class = "text-danger", id = "recaptchaMessages" })
</div>

@section Scripts {
    <recaptcha-script validation-message-element-id="recaptchaMessages" />
}


```

**Comment by PaulMiami** [comment]
You can look at [this](https://github.com/PaulMiami/reCAPTCHA/blob/master/sample/TestWebApp/Views/TestEmailNewsletterSignup/Index.cshtml) for an example

**Comment by neoGeneva** [comment]
Sweet, though maybe it should have then `Html.ValidationMessage(...)` line for when there's no client side validation for whatever reason?

"[Getting started](https://github.com/PaulMiami/reCAPTCHA/wiki/Getting-started)" should be updated too, to include that example of `recaptcha-script` since the current example doesn't have the `validation-message-element-id` attribute and wont work as given.
