### ISSUE TITLE
Support module pattern for js code?

### ISSUE THREAD

**Issue by Mergasov** [PaulMiami/reCAPTCHA#26]
I use Webpack for bundling all my scripts. It uses the module pattern under the hood, isolating client-side logic into its scope. So jQuery is not visible in global space. But [RecaptchaScriptTagHelper](https://github.com/PaulMiami/reCAPTCHA/blob/master/src/PaulMiami.AspNetCore.Mvc.Recaptcha/TagHelpers/RecaptchaScriptTagHelper.cs#L19) is relied on global-defined $ function.
I could implement some script with the logic like from RecaptchaScriptTagHelper. But in this case I need to inject  validation-message-element-id and error message to both the new script and recaptcha configuration. 
Any chance of supporting it in the future?

**Comment by PaulMiami** [comment]
This is designed to support the way MS implemented client validation with jquery validation out of the box. For other scenarios you can disable that functionality and hookup your own client validation.
```html
<recaptcha-script jquery-validation="false" />
```
