### ISSUE TITLE
Cannot read property 'setDefaults' of undefined error is thrown

### ISSUE THREAD

**Issue by mkvalluri** [PaulMiami/reCAPTCHA#28]
Hi,
Thanks for the library. From the last 2 days, I started getting "Cannot read property 'setDefaults' of undefined" when I was looking in console. Any idea on why this is happening?

**Comment by PaulMiami** [comment]
Hi,
Sounds like you are missing the jquery validation lib
Make sure you have the js dependencies includes in your page like [this](https://github.com/PaulMiami/reCAPTCHA/blob/master/sample/TestWebApp/Views/Shared/_Layout.cshtml#L43)
Or disable jquery validation
```html
<recaptcha-script jquery-validation="false" />
```

**Comment by mkvalluri** [comment]
Yeah. I have those. This came up after couple of days of using the library actually.

**Comment by mkvalluri** [comment]
Got it working. While refactoring by mistake I places this in _layout. Once I moved it back to registration pages, everything worked. Thanks :)
