### ISSUE TITLE
ArgumentException: The 'SiteKey' option must be provided.

### ISSUE THREAD

**Issue by lifescream** [PaulMiami/reCAPTCHA#3]
Hi,

I keep getting "ArgumentException: The 'SiteKey' option must be provided." even though the key provided in the ConfigureServices. I use MVC Core 1.1.   Any ideas what the problem might be?

Regards,
Dirk

**Comment by PaulMiami** [comment]
Hi,

If you use the Configuration, like in the [sample code](https://github.com/PaulMiami/reCAPTCHA/blob/master/sample/TestWebApp/Startup.cs#L33) or [the documentation](https://github.com/PaulMiami/reCAPTCHA/wiki/Getting-started), try do place a debug point in the ConfigureServices Method and inspect the value of "Configuration["Recaptcha:SiteKey"]".

Thanks,
Paul

**Comment by koopermark** [comment]
Hi, 

I have the same problem, when testing. I have followed this link http://stackoverflow.com/a/38487085 and also on your wiki page.
I have localhost added to google too.
I have added the site key and secret key as follows.

SiteKey = Configuration["key info placed here"],
SecretKey = Configuration["key info placed here"],
ValidationMessage = "Are you a robot?"

I get the following error
An unhandled exception occurred while processing the request.
ArgumentException: The 'SiteKey' option must be provided.
PaulMiami.AspNetCore.Mvc.Recaptcha.Guards.CheckMandatoryOption(string s, string name)

I am using 
"Microsoft.NETCore.App": {
      "version": "1.1.0",

King Regards
Mark

**Comment by PaulMiami** [comment]
Hi,

It seems to me like an issue with using the Configuration object and that you are getting null out of:
`Configuration["key info placed here"]`
Try to hard code the value just for testing, to rule out any other issues and then look at the configuration to understand why you are not getting the expected values.

Thanks,
Paul

**Comment by rready** [comment]
Did this every get resolved?

**Comment by PaulMiami** [comment]
Hi,

This is all pointing to a issue with your configuration, try not to use the "Configuration" object and just hard code the "SiteKey" and "SecretKey" values. Once that works, circle back to the Configuration object and debug the values coming out of it.

Thanks,
Paul

**Comment by rready** [comment]
Thanks
