### ISSUE TITLE
ReCaptcha not validating  on Ajax post Request

### ISSUE THREAD

**Issue by onurcanyilmaz** [PaulMiami/reCAPTCHA#41]
Hello,

I want to use Recaptcha on ajax request in ASP.NET CORE MVC app,

I use to  `<recaptcha />`  and  `<recaptcha-script />` on .`cshtml` page , recaptcha working but `ModelState.IsValid` everytime `false`,

```csharp
        [ValidateRecaptcha]
        [HttpPost]
        [Route("save-document")]
        public async Task<JsonResult> Save(string content)
        {
            await Task.CompletedTask;
            if (!ModelState.IsValid) // everytime false
            {
                return Json(nameof(Task));
            }
               return Json(null);
        }
```

can you help me ? 
thanks.

**Comment by onurcanyilmaz** [comment]
Hello again,

i did resolved issue, here;
https://github.com/PaulMiami/reCAPTCHA/issues/10

```javascript
    $('form').serialize(); 
   // g-recaptcha-response  : key
```
this code gave me g-recaptcha-response.

thanks.

**Comment by vanpyrzericj** [comment]
For future folks who find this, you can also manually pull the value via
```(javascript)
grecaptcha.getResponse()
```
